### ISSUE TITLE
Pretty damn comprehensive

### ISSUE THREAD

**Issue by gam-ragnar** [nicolaslopezj/roles#1]
Excellent job Amigo

**Comment by nicolaslopezj** [comment]
Thanks! 
Its great news that is comprehensive.
I you wan't to help, you can check for errors on the README file

**Comment by gam-ragnar** [comment]
I will wait until I start testing the new branch then I can do a better job with the readme file. Is this okay by you?

**Comment by nicolaslopezj** [comment]
Thats perfect
