### ISSUE TITLE
Error: When the modifier option is true, validation object must have at least one operator

### ISSUE THREAD

**Issue by shingo0620** [nicolaslopezj/roles#18]
when calling Roles.addUserToRoles got this error, I think it caused by the schema that I declare with collection2? is it possible to call operation of Roles with out any schema validate?

There are the complete error message with meteor shell

> Roles.addUserToRoles('sDpAmDEAPQZQv2T4T', 'admin')
> Error: When the modifier option is true, validation object must have at least one operator
>     at checkModifier (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2293:1)
>     at doValidation1 (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2343:1)
>     at doValidation (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2758:1)
>     at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate](packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:2793:1)
>     at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:372:1)
>     at [object Object].Mongo.Collection.(anonymous function) [as update](packages/aldeed_collection2/packages/aldeed_collection2.js:177:1)
>     at Object.Roles.addUserToRoles (packages/nicolaslopezj:roles/roles_server.js:34:23)
>     at [object Object]:1:-55
>     at Script.(anonymous function) [as runInThisContext](vm.js:41:22)
>     at /Users/shingo0620/Documents/Work/project-core/.meteor/local/build/programs/server/shell-server.js:366:27

**Comment by shingo0620** [comment]
I fixed it by adding these codes to my user schema
`roles: {
      type: [String],
      optional: true
    }`

**Comment by nicolaslopezj** [comment]
Great!
