### ISSUE TITLE
Meteor 1.3.3

### ISSUE THREAD

**Issue by lukastheiler** [nicolaslopezj/roles#20]
Hi, 

its not yet compatible with Meteor 1.3.3
nicolaslopezj:roles           1.5.3\* The most advanced roles package for meteor

thanks! Lukas

**Comment by lukastheiler** [comment]
Strange: `meteor update nicolaslopezj:roles`did not work, but when I just git clone it into the packages folder, it works fine.

**Comment by nicolaslopezj** [comment]
Try with the version 2.2.0
