### ISSUE TITLE
Uploading files issue

### ISSUE THREAD

**Issue by nisdis** [nicolaslopezj/roles#21]
Hi Nicolas,

I'm working with orionjs with the microscope boilerplate, after upgrading to meteor 1.3.3 I am unable to upload files unless admin, here is the error:

> Uncaught Error: The user has no permission to perform this action [unauthorized] - roles.js:292

I have configured 2 users: user and admin. It was working well before the upgrade
What can I do to solve this. Any help is appreciated.

Thanks.

**Comment by nicolaslopezj** [comment]
Hi,

You should give the role permission to the action `filesystem.upload` 
See https://github.com/orionjs/orion/blob/master/packages/filesystem/filesystem.js#L1.

**Comment by nisdis** [comment]
Thank you, Nicolas.
