### ISSUE TITLE
Role 'admin' already defined

### ISSUE THREAD

**Issue by aldofunes** [nicolaslopezj/roles#22]
Hello,

I am having problems defining roles. I get the following error:

```
Error: "admin" role is already defined
at new Roles.Role (packages/nicolaslopezj:roles/roles.js:90:11)
at meteorInstall.lib.roles.js (lib/roles.js:3:19)
```

Here is my /lib/roles.js file

```
import {Roles} from 'meteor/nicolaslopezj:roles';

const AdminRole = new Roles.Role('admin');
const EditorRole = new Roles.Role('editor');
const AuthorRole = new Roles.Role('author');
const SubscriberRole = new Roles.Role('subscriber');

export {AdminRole, EditorRole, AuthorRole, SubscriberRole};
```

There is no other file in which I define a role. Not even users added to admin role.

If I change the name to `admin2` or something else, no errors are thrown.

Is there already a definition for admin role?

**Comment by nicolaslopezj** [comment]
Hi!

The admin role is a special role, which is defined by default.

https://github.com/nicolaslopezj/roles/blob/master/roles.js#L318

``` js
import {Roles} from 'meteor/nicolaslopezj:roles'

const AdminRole = Roles.adminRole
```

**Comment by aldofunes** [comment]
Oh, nice.

Thank you
