### ISSUE TITLE
Uncaught Helper "collections.projects.forbiddenFields" is not defined.

### ISSUE THREAD

**Issue by mathieutozer** [nicolaslopezj/roles#7]
How do I use this forbidden fields feature? I have tried googling around a bit but don't see any documentation. I've just removed insecure and now my orion admin panel cannot even insert new documents into my collection without throwing Uncaught Helper "collections.projects.forbiddenFields" is not defined.

I am using orion, but not explicitly using attachRoles (any more than what the blog example comes with).

As discussed in: https://github.com/nicolaslopezj/roles/commit/e98ce1eab96b6f92c4c7f638963556f8d44b18b2

**Comment by nicolaslopezj** [comment]
Can I see your code?

**Comment by mathieutozer** [comment]
Sent it to you via email, as it's not open source and I am not sure which snippet you are interested in seeing!

Edit: Your email bounced. Here's a gist of everything in orion/collections 

https://gist.github.com/mathieutozer/6ccad0bdfd3a2b437865

I should note that there isn't much else to the app - I'm writing a native client in obj-c so everything else is basically the blog example.

**Comment by nicolaslopezj** [comment]
I can't see any error there, please try again sending the repo.

My email is nicolaslopezj@me.com

**Comment by BudickDa** [comment]
Had the same problem after the update to meteor 1.2. 
I had to update nicolaslopezj:roles manually with `meteor update nicolaslopezj:roles`
